title: Shadman Shahriar
description: Hi
url: "https://shadman-shahriar.github.io"
markdown: kramdown
theme: minima

# Collections
collections:
  projects:
    output: true
  blog:
    output: tru
    
exclude:
  - README.md
