# Site settings
title: Shadman Shahriar
description: I am Shadman Shahriar & I am an Electronics Engineer
I have over 10 years of experience in electronic design and development. I am skilled in tools like Altium, Eagle, Proteus, and EasyEDA. My expertise includes microcontroller programming and embedded systems design. I also have experience in manufacturing, quality assurance, and collaborating with software engineers. I am highly motivated, deadline-oriented, and focused on delivering high-quality results.  
baseurl: "Portfolio" # the subpath of your site, e.g. /blog
url: "https://shadman-shahriar.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima # or your custom theme

# Collections
collections:
  projects:
    output: true
  blog:
    output: true

# Exclude files/folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/blog/page:num"
