title: Shadman Shahriar
description: Hi
url: "https://shadman-shahriar.github.io"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
